name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Environment validation
        run: |
          export NODE_ENV=production
          export VITE_API_URL="${VITE_API_URL:-https://api.example.com}"
          export VITE_FIREBASE_API_KEY="${VITE_FIREBASE_API_KEY:-placeholder}" 
          export VITE_FIREBASE_PROJECT_ID="${VITE_FIREBASE_PROJECT_ID:-placeholder}" 
          export VITE_FIREBASE_APP_ID="${VITE_FIREBASE_APP_ID:-1:000:web:placeholder}" 
          npm run validate-env
        # To inject real values, define repository/environment secrets and add an 'env:' block mapping them.

      - name: Type check
        run: npm run type-check

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test -- --ci --reporter=default

      - name: Build
        run: npm run build
