# .github/workflows/ci.yml
name: Monorepo CI/CD
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Backend Dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
      - name: Run Backend Tests
        run: |
          cd backend
          pytest
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm ci || echo "npm ci failed, check logs above"
          npm list @testing-library/jest-dom || echo "Failed to list @testing-library/jest-dom"
      - name: Debug Test Setup
        run: |
          cd frontend
          ls -la src
          cat src/setupTests.js || echo "src/setupTests.js not found"
      - name: Run Frontend Tests
        run: |
          cd frontend
          npm run test || echo "Frontend tests failed, check logs above"
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_BACKEND_URL: https://astrology-app-0emh.onrender.com
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
  deploy-frontend:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Debug Directory Structure
        run: |
          pwd
          ls -la
          cat .env || echo ".env not found"
          echo "Node version:"
          node --version
          echo "NPM version:"
          npm --version
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install Vercel CLI
        run: npm install -g vercel@44.7.0
      - name: Debug Vercel Token and Environment
        run: |
          if [ -z "$VERCEL_TOKEN" ]; then
            echo "Error: VERCEL_TOKEN is not set"
            exit 1
          else
            echo "VERCEL_TOKEN is set"
          fi
          echo "VITE_FIREBASE_API_KEY is set: $([[ -n "$VITE_FIREBASE_API_KEY" ]] && echo 'yes' || echo 'no')"
          echo "VITE_FIREBASE_AUTH_DOMAIN is set: $([[ -n "$VITE_FIREBASE_AUTH_DOMAIN" ]] && echo 'yes' || echo 'no')"
          echo "VITE_FIREBASE_PROJECT_ID is set: $([[ -n "$VITE_FIREBASE_PROJECT_ID" ]] && echo 'yes' || echo 'no')"
          echo "VITE_FIREBASE_STORAGE_BUCKET is set: $([[ -n "$VITE_FIREBASE_STORAGE_BUCKET" ]] && echo 'yes' || echo 'no')"
          echo "VITE_FIREBASE_MESSAGING_SENDER_ID is set: $([[ -n "$VITE_FIREBASE_MESSAGING_SENDER_ID" ]] && echo 'yes' || echo 'no')"
          echo "VITE_FIREBASE_APP_ID is set: $([[ -n "$VITE_FIREBASE_APP_ID" ]] && echo 'yes' || echo 'no')"
          echo "VITE_BACKEND_URL=$VITE_BACKEND_URL"
          echo "VITE_API_KEY is set: $([[ -n "$VITE_API_KEY" ]] && echo 'yes' || echo 'no')"
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_BACKEND_URL: https://astrology-app-0emh.onrender.com
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
      - name: Clear Vercel Cache
        run: vercel cache purge --project $VERCEL_PROJECT_ID --token=$VERCEL_TOKEN
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      - name: Build and Debug Output
        run: |
          npm ci || echo "npm ci failed, check logs above"
          npm list || echo "Failed to list dependencies"
          npm run build --verbose || echo "Build failed, check logs above"
          ls -la dist || echo "dist directory not found"
          cat dist/index.html || echo "dist/index.html not found"
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_BACKEND_URL: https://astrology-app-0emh.onrender.com
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
      - name: Deploy to Vercel
        run: |
          vercel deploy --prod --token=$VERCEL_TOKEN --confirm --cwd . --project $VERCEL_PROJECT_ID --log=debug
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_BACKEND_URL: https://astrology-app-0emh.onrender.com
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
  deploy-backend:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
        env:
          API_KEY: ${{ secrets.API_KEY }}
          LOG_FILE: logs/app.log
          PORT: 8000
          EPHE_PATH: /app/ephe
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}